apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dohelmoto.fullname" . }}-config
  namespace: {{ include "dohelmoto.namespace" . }}
  labels:
    {{- include "dohelmoto.labels" . | nindent 4 }}
    component: config
data:
  {{- toYaml .Values.configMap.data | nindent 2 }}
