apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dohelmoto.fullname" . }}-secrets
  namespace: {{ include "dohelmoto.namespace" . }}
  labels:
    {{- include "dohelmoto.labels" . | nindent 4 }}
    component: secrets
type: Opaque
data:
  {{- toYaml .Values.secret.data | nindent 2 }}
